version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: ciaca_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: ciaca_backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GROQ_MODEL=${GROQ_MODEL}
      - APP_TOKEN=${APP_TOKEN}
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongodb
    volumes:
      - ./data:/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: ciaca_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  mongo_data: